<?php

/**
 * Implements hook_entity_presave().
 */
use Drupal\taxonomy\Entity\Term;
function filemanagement_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
	$user_id = \Drupal::currentUser()->id();
	//$var = $entity->bundle();

  switch ($entity->bundle()) {
    // Here you modify only your day content type
    case 'user_files':
			$file_tax_id = $entity->get('field_folder_name')->getValue();
			$tid = $file_tax_id[0]['target_id'];
			$term = Term::load($tid);
			$authore_ar = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($tid)->get('field_folder_author')->getValue();
			$authors = array_column($authore_ar, 'target_id');
			if(!in_array($user_id, $authors)) {
				$term->field_folder_author[] = ['target_id' => $user_id];	
			}
			$term->Save();

     break;
  }
}

/**
 * Implements hook_theme().
 */
function filemanagement_theme($existing, $type, $theme, $path) {
  return [
    'filefolderlist' => [
      'variables' => ['folders' => NULL],
    ],
  ];
}

/* function filemanagement_element_info_alter(array &$types) {
	echo '<pre>'; print_r($types); echo '</pre>'; exit;
  if (isset($types['table'])) {
    $types['table']['#attached']['library'][] = 'your_module/library_name';
  }
} */